import React, { ReactNode } from 'react';
import Provider from './components/Provider';
import './globals.css';

// Define your metadata and component
interface Metadata {
  title: string;
  description: string;
}

export const metadata: Metadata = {
  title: 'Blog app by Abdulahi😁',
  description: 'Generated by create next app',
};



interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body>
      <Provider>
        {children}
      </Provider>
      </body>

    </html>
  );
}

